# -*- coding: utf-8 -*-
"""agents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QY-xBuSvbgPo31NiO0gYI3ou6YDmW3nu
"""

# -*- coding: utf-8 -*-
import random
import time
import copy
import pickle

#Edited to add QLearningAgent, search/random agents kept the same

# ==========================================
# BASELINE AGENTS
# ==========================================

class RandomAgent:
    def get_move(self, game, player):
        '''Selects a move at random from all empty cells'''
        legal_moves = game.get_legal_moves()
        if not legal_moves:
            return None
        return random.choice(legal_moves)

class NoisyHeuristicAgent: #Edited to optimize evaluation by checking for a 4 line win and temporarily placing a block
    def __init__(self):
        """
        Precomputes all 28 possible 4-cell winning lines on a 5x5 board
        and maps each coordinate to only the lines passing directly through it.
        """
        self.cell_to_windows = {(r, c): [] for r in range(5) for c in range(5)}

        # 1. Precompute Horizontal Windows
        for r in range(5):
            for c in range(2):
                window = [(r, c+i) for i in range(4)]
                for cell in window:
                    self.cell_to_windows[cell].append(window)

        # 2. Precompute Vertical Windows
        for c in range(5):
            for r in range(2):
                window = [(r+i, c) for i in range(4)]
                for cell in window:
                    self.cell_to_windows[cell].append(window)

        # 3. Precompute Main Diagonal Windows (Top-Left to Bottom-Right)
        for r in range(2):
            for c in range(2):
                window = [(r+i, c+i) for i in range(4)]
                for cell in window:
                    self.cell_to_windows[cell].append(window)

        # 4. Precompute Anti-Diagonal Windows (Bottom-Left to Top-Right)
        for r in range(3, 5):
            for c in range(2):
                window = [(r-i, c+i) for i in range(4)]
                for cell in window:
                    self.cell_to_windows[cell].append(window)

    def get_move(self, game, player):
        '''With probability epsilon 0.2, plays a random move. Otherwise uses a heuristic.'''
        legal_moves = game.get_legal_moves()

        if random.random() < 0.2:
            return random.choice(legal_moves)

        return self.heuristic_move(game, player, legal_moves)

    def heuristic_move(self, game, player, legal_moves):
        '''Heuristic based on prioritizing winning, blocking, preferring center, or random'''
        opponent = 'O' if player == 'X' else 'X'

        # Immediate win detection using localized checks
        for move in legal_moves:
            if self.simulates_win(game, move, player):
                return move

        # Blocking opponent's win using localized checks
        for move in legal_moves:
            if self.simulates_win(game, move, opponent):
                return move

        # Prioritizing center and inner ring
        center_preferences = [(2,2), (1,1), (1,2), (1,3), (2,1), (2,3), (3,1), (3,2), (3,3)]
        for move in center_preferences:
            if move in legal_moves:
                return move

        return random.choice(legal_moves)

    def simulates_win(self, game, move, test_player):
        """
        Highly efficient local win check.
        Instead of modifying the board array or running full grid scans,
        it verifies if any precomputed line containing this cell already has 3 marks.
        """
        # Fetch only the winning lines that pass through this specific candidate coordinate
        for window in self.cell_to_windows[move]:
            match_count = 0
            for r, c in window:
                if (r, c) == move:
                    continue
                if game.board[r][c] == test_player:
                    match_count += 1
                else:
                    # If any other cell contains an opponent mark or is blank,
                    # this specific line cannot be an immediate win scenario.
                    break

            # If the other 3 cells in this line are already held by the player, it's a win!
            if match_count == 3:
                return True

        return False

    """def heuristic_move(self, game, player, legal_moves): # FIXED: Added colon and legal_moves arg
        '''Heuristic based on prioritizing winning, blocking, preferring center, or random'''
        opponent = 'O' if player == 'X' else 'X' # FIXED: == instead of =

        # Immediate win detection
        for move in legal_moves:
            if self.simulates_win(game, move, player):
                return move

        # Blocking opponent's win
        for move in legal_moves:
            if self.simulates_win(game, move, opponent):
                return move

        # Prioritizing center and inner ring
        center_preferences = [(2,2), (1,1), (1,2), (1,3), (2,1), (2,3), (3,1), (3,2), (3,3)]
        for move in center_preferences:
            if move in legal_moves:
                return move

        return random.choice(legal_moves)

    def simulates_win(self, game, move, test_player):
        '''Helper to test if a move results in a win.'''
        row, col = move
        game.board[row][col] = test_player
        is_win = game.check_winner(test_player)
        game.board[row][col] = game.empty_cell # FIXED: row, col instead of r, c
        return is_win"""


# ==========================================
# ALPHA-BETA AGENT
# ==========================================

class TimeoutException(Exception):
    pass

class AlphaBetaAgent:
    def __init__(self, depth_limit=4, time_limit=3.0):
        self.depth_limit = depth_limit
        self.time_limit = time_limit
        self.start_time = 0
        self.nodes_expanded = 0

    def get_move(self, game, player):
        """This acts as the ALPHA-BETA-SEARCH function from the slide."""
        self.start_time = time.time()

        try:
            utility, move = self.max_value(game, self.depth_limit, -float('inf'), float('inf'), player)
            if move is not None:
                return move
            else:
                return random.choice(game.get_legal_moves())
        except TimeoutException:
            legal_moves = game.get_legal_moves()
            return random.choice(legal_moves) if legal_moves else None

    def max_value(self, game, depth, alpha, beta, player):
        """Returns a (utility, move) pair for the maximizing player."""
        self.check_time()
        self.nodes_expanded += 1

        opponent = 'O' if player == 'X' else 'X'

        if game.check_winner(player): return (10000 + depth, None)
        if game.check_winner(opponent): return (-10000 - depth, None)
        if not game.get_legal_moves(): return (0, None)
        if depth == 0: return (self.evaluate(game, player), None)

        v = -float('inf')
        best_move = None

        for move in game.get_legal_moves():
            row, col = move
            game.board[row][col] = player

            v2, _ = self.min_value(game, depth - 1, alpha, beta, player)
            game.board[row][col] = game.empty_cell

            if v2 > v:
                v = v2
                best_move = move
                alpha = max(alpha, v)
            if v >= beta:
                return v, best_move

        return v, best_move

    def min_value(self, game, depth, alpha, beta, player):
        """Returns a (utility, move) pair for the minimizing opponent."""
        self.check_time()
        self.nodes_expanded += 1

        opponent = 'O' if player == 'X' else 'X'

        if game.check_winner(player): return (10000 + depth, None)
        if game.check_winner(opponent): return (-10000 - depth, None)
        if not game.get_legal_moves(): return (0, None)
        if depth == 0: return (self.evaluate(game, player), None)

        v = float('inf')
        best_move = None

        for move in game.get_legal_moves():
            row, col = move
            game.board[row][col] = opponent

            v2, _ = self.max_value(game, depth - 1, alpha, beta, player)
            game.board[row][col] = game.empty_cell

            if v2 < v:
                v = v2
                best_move = move
                beta = min(beta, v)
            if v <= alpha:
                return v, best_move

        return v, best_move

    def check_time(self):
        """Throws an error if we are dangerously close to the 3-second limit."""
        if time.time() - self.start_time > (self.time_limit - 0.1):
            raise TimeoutException()

    # ==========================================
    # EVALUATION FUNCTION & HELPERS
    # ==========================================
    def evaluate(self, game, player):
        score = 0
        opponent = 'O' if player == 'X' else 'X'

        # 1. Evaluate Center Control.
        center_weights = [
            [1, 1, 1, 1, 1],
            [1, 5, 5, 5, 1],
            [1, 5, 10, 5, 1],
            [1, 5, 5, 5, 1],
            [1, 1, 1, 1, 1]
        ]
        for r in range(5):
            for c in range(5):
                if game.board[r][c] == player:
                    score += center_weights[r][c]
                elif game.board[r][c] == opponent:
                    score -= 2 * center_weights[r][c]

        # 2 & 3. Evaluate Threats and Blocking
        windows = self.get_all_windows_of_4(game)

        for window in windows:
            score += self.score_window(window, player, opponent, game.empty_cell)

        return score

    # FIXED: Moved out of evaluate() to be its own peer method
    def get_all_windows_of_4(self, game):
        """Extracts all possible 4-cell lines (windows) from the 5x5 board."""
        windows = []
        board = game.board

        # 1. Horizontal windows
        for r in range(5):
            for c in range(2):
                current_window = []
                for i in range(4):
                    current_window.append(board[r][c+i])
                # FIXED: Outdented
                windows.append(current_window)

        # 2. Vertical windows
        for c in range(5):
            for r in range(2):
                current_window = []
                for i in range(4):
                    current_window.append(board[r+i][c])
                # FIXED: Outdented
                windows.append(current_window)

        # 3. Diagonals
        for r in range(2):
            for c in range(2):
                current_window = []
                for i in range(4):
                    current_window.append(board[r+i][c+i])
                # FIXED: Outdented
                windows.append(current_window)

        # 4. Anti-diagonals
        for r in range(3, 5):
            for c in range(2):
                current_window = []
                for i in range(4):
                    current_window.append(board[r-i][c+i])
                # FIXED: Outdented
                windows.append(current_window)

        return windows

    # FIXED: Added empty_cell argument so it knows what to look for
    def score_window(self, window, player, opponent, empty_cell):
        player_count = window.count(player)
        opp_count = window.count(opponent)
        empty_count = window.count(empty_cell)

        # Give points for your open threats
        if player_count == 3 and empty_count == 1:
            return 100
        elif player_count == 2 and empty_count == 2:
            return 10

        # Subtract heavily for opponent threats
        if opp_count == 3 and empty_count == 1:
            return -200
        if opp_count == 2 and empty_count == 2:
            return -20

        # Dead lines, no points (FIXED: added colon)
        else:
            return 0

# ==========================================
# QLEARNINGAGENT
# ==========================================

#Class name must be QLearningAgent.
#Initialize the tabular Q-learning agent. Add justification why values of alpha and gamma are used
class QLearningAgent:
  def __init__(self, alpha=0.1, gamma=0.95, use_symmetry=True):
    self.alpha = alpha
    self.gamma = gamma
    self.use_symmetry = use_symmetry
    self.q_table = {} # Use a Sparse Q-table
    #Layout: self.q_table[state_tuple][action_tuple] = q_value

  def _transform_state(self, state, config_idx):
    """Apply one of the 8 dihedral group (D4)
    symmetry transformations to a flat 25 board tuple representation"""
# Use a Sparse Q-table
    grid = [state[i:i+5] for i in range(0, 25, 5)]

    if config_idx == 0:
      return state
    elif config_idx == 1: # Rotation 90° Clockwise
      return tuple(grid[4-c][r] for r in range(5) for c in range(5))
    elif config_idx == 2: # Rotation 180°
      return tuple(grid[4-r][4-c] for r in range(5) for c in range(5))
    elif config_idx == 3: # Rotation 270°
      return tuple(grid[c][4-r] for r in range(5) for c in range(5))
    elif config_idx == 4: # Horizontal Flip
      return tuple(grid[r][4-c] for r in range(5) for c in range(5))
    elif config_idx == 5: # Vertical Flip
      return tuple(grid[4-r][c] for r in range(5) for c in range(5))
    elif config_idx == 6: # Transpose Diagonal
      return tuple(grid[c][r] for r in range(5) for c in range(5))
    elif config_idx == 7: # Anti-Transpose Diagonal
      return tuple(grid[4-c][4-r] for r in range(5) for c in range(5))


  def _to_canonical(self, state, action):
        """
        Transforms a state-action pair into its unique canonical representation
        by finding the lexicographically smallest state tuple variant.
        """
        if not self.use_symmetry:
            return state, action

        r, c = action
        # Map how the coordinate (r, c) alters under each of the 8 grid transforms
        trans_actions = [
            (r, c), (c, 4-r), (4-r, 4-c), (4-c, r),
            (r, 4-c), (4-r, c), (c, r), (4-c, 4-r)
        ]

        canonical_state = None
        canonical_action = None

        for i in range(8):
            t_state = self._transform_state(state, i)
            if canonical_state is None or t_state < canonical_state:
                canonical_state = t_state
                canonical_action = trans_actions[i]

        return canonical_state, canonical_action

  def get_q(self, state, action):
      """Safely fetches a Q-value, defaulting unseen values to 0 (Section 3.3 & 4.1)."""
      c_state, c_action = self._to_canonical(state, action)
      if c_state not in self.q_table:
          return 0.0
      return self.q_table[c_state].get(c_action, 0.0)

  def set_q(self, state, action, value):
      """Assigns a calculated Q-value to the sparse canonical state key."""
      c_state, c_action = self._to_canonical(state, action)
      if c_state not in self.q_table:
          self.q_table[c_state] = {}
      self.q_table[c_state][c_action] = value

  def _get_legal_actions_from_state(self, state):
      """Helper to extract legal coordinate moves from an active perspective state."""
      legal = []
      for idx, val in enumerate(state):
          if val == 0:  # 0 denotes an empty cell
              legal.append((idx // 5, idx % 5))
      return legal

  # --- 1. Epsilon-Greedy Action Selection (Section 4.1 Requirement) ---
  def select_action(self, state, legal_actions, epsilon):
      """
      Selects an action using an epsilon-greedy policy over legal actions.
      Set epsilon = 0 manually during evaluation modes (Section 3.3).
      """
      if not legal_actions:
          return None

      # Exploration phase
      if random.random() < epsilon:
          return random.choice(legal_actions)

      # Exploitation phase (Greedy Q choice)
      q_values = [self.get_q(state, a) for a in legal_actions]
      max_q = max(q_values)

      # Section 4.1: Break ties uniformly at random
      best_actions = [a for a, q in zip(legal_actions, q_values) if q == max_q]
      return random.choice(best_actions)

  # --- 2. Temporal Difference Q-Learning Update (Section 3.3 Requirement) ---
  def update(self, state, action, reward, next_state, done):
      """
      Updates the Q-table entry following the exact Bellman optimality equation.
      Ensures strict compliance with Section 4.4 constraints.
      """
      current_q = self.get_q(state, action)

      if done:
          # Section 4.4 Mistake Guard: Target is only the reward if terminal
          target = reward
      else:
          # Section 4.4 Mistake Guard: Max over LEGAL actions only
          next_legal = self._get_legal_actions_from_state(next_state)
          if next_legal:
              max_next_q = max([self.get_q(next_state, a_prime) for a_prime in next_legal])
          else:
              max_next_q = 0.0

          # Section 3.3: Target calculation formula
          target = reward + self.gamma * max_next_q

      # Standard TD update equation: Q(s,a) = Q(s,a) + alpha * (target - Q(s,a))
      new_q = current_q + self.alpha * (target - current_q)
      self.set_q(state, action, new_q)

  # --- 3. Save/Load Model Artifacts (Section 4.1 Requirement) ---
  def save_q_table(self, filepath):
      """Saves the sparse dictionary to disk using Pickle serialization."""
      with open(filepath, 'wb') as f:
          pickle.dump(self.q_table, f)
      print(f"Successfully saved Q-table containing {len(self.q_table)} state keys.")

  def load_q_table(self, filepath):
      """Loads a pre-trained sparse dictionary from disk."""
      with open(filepath, 'rb') as f:
          self.q_table = pickle.load(f)
      print(f"Successfully loaded Q-table containing {len(self.q_table)} state keys.")

# ==========================================
# Reinforcement Learning
# ==========================================

#Agent can be X or O

#Hyperparameters: 50000 training episodes, alpha 0.10, gamma 0.95, epsilon starting at 1.0 and decaying to 0.05 (add justification)
#Must include random.seed()

# ==========================================
# Opponents and baselines
# ==========================================

#Requirements: RandomAgent (baseline and evaluation), NoisyHeuristicAgent (improved training and evaluation),
#Mixed opponent (improved training), AlphaBetaAgent (only for evaluation/comparison)

# ==========================================
# Required training plan
# ==========================================

#Training configuration 1 using RandomAgent and terminal rewards only (baseline)
#Training configuration 2 using NoisyHeuristicAgent
#Mixed opponent (changes once per episode, not after every move). keep each game coherent and make results easier to interpret

#Do not include: illegal moves in max Q, wrong terminal update, mixing X and O states incorrectly, letting QLearningAgent use AlphaBetaAgent, changing mixed opponents every move