# -*- coding: utf-8 -*-
"""evaluate

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16pBTbOnl2-MOqx5NE4t0iEpOuRURSKOz
"""

# -*- coding: utf-8 -*-
"""
evaluate.py - Full Refactored Execution Engine
Tracks Summary Metrics: AvgEvaluationReturn and AvgGameLengthMoves
"""
#Indentation standardized to 4 spaces

import os
import csv
import random
import pickle
import numpy as np
from game import TicTacToe5x5
from agents import QLearningAgent, RandomAgent, NoisyHeuristicAgent, AlphaBetaAgent

def run_evaluation_suite(q_table_path, opponent_agent, opponent_name, num_games=100):
    """
    Evaluates a frozen Q-table against a specific benchmark opponent.
    Strictly adheres to the metric and seed rules (seed is fixed).
    """
    agent = QLearningAgent(use_symmetry=True)
    try:
        agent.load_q_table(q_table_path)
    except FileNotFoundError:
        print(f"❌ Error loading Q-table from {q_table_path}.")
        return []

    epsilon = 0.0  # Section 5.1 Mandate: Pure greedy policy evaluation
    env = TicTacToe5x5()

    # Track metrics
    win_count = 0
    draw_count = 0
    loss_count = 0
    total_return = 0.0
    total_moves = 0

    detailed_logs = []
    print(f"Evaluating {q_table_path} vs {opponent_name} over {num_games} games...")

    for i in range(num_games):
        # Enforce exact replication reproducibility anchors dictated by Section 5.1
        random.seed(i)
        np.random.seed(i)

        q_agent_sign = 'X' if i < (num_games // 2) else 'O'
        state = env.reset(opponent_agent=opponent_agent, q_agent_sign=q_agent_sign)

        #Agent always sees its pieces as 1.
        normalized_state = tuple(-x for x in state) if q_agent_sign == 'O' else state

        done = False
        game_moves = 0
        episode_reward = 0.0

        while not done:
            legal = env.legal_actions()
            if not legal:
                break

            action = agent.select_action(normalized_state, legal, epsilon=epsilon)

            #Follow with next state
            next_state, reward, done, _ = env.step(action)

            #Normalize the next incoming state before looping
            normalized_next_state = tuple(-x for x in next_state) if q_agent_sign == 'O' else next_state

            state = next_state
            normalized_state = normalized_next_state
            episode_reward += reward
            game_moves += 1


        # Track and document game outcomes with the perspective of the Q-agent
        if episode_reward > 0:
            win_count += 1
            outcome = "Win"
        elif episode_reward < 0:
            loss_count += 1
            outcome = "Loss"
        else:
            draw_count += 1
            outcome = "Draw"

        total_return += episode_reward
        total_moves += game_moves

        # Append row entry metadata for results.csv logging
        detailed_logs.append({
            "OpponentType": opponent_name,
            "GameIndex": i + 1,
            "QAgentSign": q_agent_sign,
            "Outcome": outcome,
            "Return": episode_reward,
            "GameLength": game_moves
        })

    # Summary statistics calculation
    win_rate = (win_count / num_games) * 100
    loss_rate = (loss_count / num_games) * 100
    draw_rate = (draw_count / num_games) * 100
    avg_return = total_return / num_games
    avg_length = total_moves / num_games

    # Inject macro summary attributes directly into row logging items
    for log_entry in detailed_logs:
        log_entry["AvgEvaluationReturn"] = round(avg_return, 4)
        log_entry["AvgGameLengthMoves"] = round(avg_length, 2)

    print(f"--- Summary Metrics vs {opponent_name} ---")
    print(f"Record: {win_count} Wins, {loss_count} Losses, {draw_count} Draws")
    print(f"Rates: Win {win_rate:.1f}% | Loss {loss_rate:.1f}% | Draw {draw_rate:.1f}%")
    print(f"Average Return: {avg_return:.4f}")
    print(f"Average Game Length: {avg_length:.2f} moves\n")

    return detailed_logs

def extract_q_table_metrics(filepath):
    try:
        with open(filepath, "rb") as f:
            q_table = pickle.load(f)
        total_states = len(q_table)
        total_state_action_pairs = sum(len(actions) for actions in q_table.values())
        print(f"=== Metrics for {filepath} ===")
        print(f"Unique states visited (Table Size): {total_states}")
        print(f"Total state-action entries stored: {total_state_action_pairs}\n")
    except FileNotFoundError:
        print(f"Could not extract metrics for {filepath}: File not found.")

def main():
    all_evaluation_records = []

    # -----------------------------------------------------------------
    # Test Suite 1: Baseline Model (Trained on Random Only)
    # -----------------------------------------------------------------
    print("=================== EVALUATING BASELINE MODEL ===================")
    all_evaluation_records.extend(run_evaluation_suite("q_table_baseline.pkl", RandomAgent(), "RandomAgent", 100))
    all_evaluation_records.extend(run_evaluation_suite("q_table_baseline.pkl", NoisyHeuristicAgent(), "NoisyHeuristicAgent", 100))
    all_evaluation_records.extend(run_evaluation_suite("q_table_baseline.pkl", AlphaBetaAgent(depth_limit=4), "AlphaBetaAgent", 30))

    # -----------------------------------------------------------------
    # Test Suite 2: Improved Model
    # -----------------------------------------------------------------
    print("=================== EVALUATING IMPROVED MODEL ===================")
    all_evaluation_records.extend(run_evaluation_suite("q_table_improved.pkl", RandomAgent(), "RandomAgent", 100))
    all_evaluation_records.extend(run_evaluation_suite("q_table_improved.pkl", NoisyHeuristicAgent(), "NoisyHeuristicAgent", 100))
    all_evaluation_records.extend(run_evaluation_suite("q_table_improved.pkl", AlphaBetaAgent(depth_limit=4), "AlphaBetaAgent", 30))

    # -----------------------------------------------------------------
    # Test Suite 3: Self-Play Model (Trained on Itself)
    # -----------------------------------------------------------------
    print("=================== EVALUATING SELF-PLAY MODEL ===================")
    all_evaluation_records.extend(run_evaluation_suite("q_table_selfplay.pkl", RandomAgent(), "RandomAgent", 100))
    all_evaluation_records.extend(run_evaluation_suite("q_table_selfplay.pkl", NoisyHeuristicAgent(), "NoisyHeuristicAgent", 100))
    all_evaluation_records.extend(run_evaluation_suite("q_table_selfplay.pkl", AlphaBetaAgent(depth_limit=4), "AlphaBetaAgent", 30))

    # Save and output everything smoothly
    if all_evaluation_records:
        # FIXED: Added the two missing fields to map header criteria correctly
        csv_columns = [
            "OpponentType",
            "GameIndex",
            "QAgentSign",
            "Outcome",
            "Return",
            "GameLength",
            "AvgEvaluationReturn",
            "AvgGameLengthMoves"
        ]
        with open("results.csv", "w", newline="", encoding="utf-8") as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=csv_columns)
            writer.writeheader()
            for data in all_evaluation_records:
                writer.writerow(data)
        print("✅ Metric tracking successfully exported and written to results.csv!")

        print("\n=================== TABLE COMPRESSION METRICS ===================")
        extract_q_table_metrics("q_table_baseline.pkl")
        extract_q_table_metrics("q_table_improved.pkl")
        extract_q_table_metrics("q_table_selfplay.pkl")


if __name__ == "__main__":
    main()

    # ==========================================
    # Visualizations / State Analysis Extraction Tools
    # ==========================================
    print("\n=================== STATE ANALYSIS HEATMAP DATA ===================")
    eval_agent = QLearningAgent(use_symmetry=True)

    try:
        # Load the improved table to pull valid, learned metrics for the report
        eval_agent.load_q_table("q_table_improved.pkl")

        # Define a sample early-game matrix for evaluation
        sample_state = (
            -1,  0,  0,  0,  0,
             0,  0,  0,  0,  0,
             0,  0,  1,  0,  0,
             0,  0,  0,  0,  0,
             0,  0,  0,  0,  0
        )

        print("Extracting learned actions for the sample state...")

        for r in range(5):
            row_output = []
            for c in range(5):
                idx = r * 5 + c
                if sample_state[idx] == 0:
                    q_value = eval_agent.get_q(sample_state, (r, c))
                    row_output.append(f"({r},{c}): {q_value:.3f}")
                else:
                    row_output.append(f"({r},{c}): Taken ")
            print(" | ".join(row_output))

    except FileNotFoundError:
        print("Run your training pipeline first to extract visualization values.")