# -*- coding: utf-8 -*-
"""game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ECUINBNgQo7fPgPsaOPnXWyCk528UC5y
"""

# -*- coding: utf-8 -*-
"""game.py

Polymorphic reinforcement learning environment wrapper for 5x5 Tic-Tac-Toe.
All indentation standardized to clean 4-space blocks.
"""

import random

class TicTacToe5x5:
    def __init__(self):
        # An empty board is initialized with blank spaces.
        self.board = [[' ' for _ in range(5)] for _ in range(5)]
        self.player_turn = 'X'
        self.empty_cell = ' '

        # --- Added for Reinforcement Learning Tracking ---
        self.q_agent_sign = 'X'
        self.opponent_sign = 'O'
        self.opponent_agent = None

    def reset(self, opponent_agent=None, q_agent_sign=None):
        """Resets the board to its initial state and returns initial perspective state."""
        self.board = [[' ' for _ in range(5)] for _ in range(5)]
        self.opponent_agent = opponent_agent

        # Determine signs randomly if not specified
        if q_agent_sign is None:
            self.q_agent_sign = random.choice(['X', 'O'])
        else:
            self.q_agent_sign = q_agent_sign

        self.opponent_sign = 'O' if self.q_agent_sign == 'X' else 'X'

        # FIXED: Routes opening moves polymorphically without interface attribute crashes
        if self.opponent_sign == 'X' and self.opponent_agent is not None:
            move = self._get_opponent_move()
            if move is not None:
                self.make_move(move, self.opponent_sign)

        return self.get_state()

    def get_legal_moves(self):
        """Returns a list of tuples (r, c) for all empty cells on the board."""
        moves = []
        for r in range(5):
            for c in range(5):
                if self.board[r][c] == self.empty_cell:
                    moves.append((r, c))
        return moves

    def legal_actions(self):
        """Standardized interface wrapper for learning loops."""
        return self.get_legal_moves()

    def _get_opponent_move(self):
        """Polymorphic router that handles both HW1 search classes and HW3 RL wrappers cleanly."""
        legal = self.legal_actions()
        if not legal:
            return None

        if hasattr(self.opponent_agent, 'get_move'):
            # Safely passes the environment wrapper instance (self) to Random/Heuristic/AlphaBeta
            return self.opponent_agent.get_move(self, self.opponent_sign)
        elif hasattr(self.opponent_agent, 'select_action'):
            # Coordinates with RL self-play wrappers
            return self.opponent_agent.select_action(self.get_state(), legal)
        else:
            return random.choice(legal)

    def step(self, action):
        """Executes a single environment step (Section 4.2 engine loop)."""
        # 1. Q-learning agent makes its move
        self.make_move(action, self.q_agent_sign)

        # Check if agent's move ended the game
        done, winner = self.is_terminal()
        if done:
            reward = 1.0 if winner == self.q_agent_sign else 0.0  # +1 for Win, 0 for Draw
            return self.get_state(), reward, True, {}

        # 2. Opponent makes its move if the game continues
        if self.opponent_agent is not None:
            move = self._get_opponent_move()
            if move is not None:
                self.make_move(move, self.opponent_sign)

            # Check if opponent's move ended the game
            done, winner = self.is_terminal()
            if done:
                reward = -1.0 if winner == self.opponent_sign else 0.0  # -1 for Loss, 0 for Draw
                return self.get_state(), reward, True, {}

        # Game is ongoing
        return self.get_state(), 0.0, False, {}

    def get_state(self):
        """Converts board grid to an immutable 25-tuple from the active agent's view."""
        state_list = []
        for r in range(5):
            for c in range(5):
                cell = self.board[r][c]
                if cell == ' ':
                    state_list.append(0)
                elif cell == self.q_agent_sign:
                    state_list.append(1)   # Self mark identity
                else:
                    state_list.append(-1)  # Opponent mark identity
        return tuple(state_list)

    def make_move(self, move, player):
        """Updates the board with the player's sign by taking a coordinate tuple."""
        r, c = move
        if self.board[r][c] == self.empty_cell:
            self.board[r][c] = player
            return True
        return False

    def check_winner(self, player):
        """Scans the board grid checking for sequential 4-in-a-row marks."""
        # 1. Check horizontal rows
        for row in range(5):
            for col in range(2):
                if all(self.board[row][col+i] == player for i in range(4)):
                    return True

        # 2. Check vertical columns
        for col in range(5):
            for row in range(2):
                if all(self.board[row+i][col] == player for i in range(4)):
                    return True

        # 3. Check diagonals (top-left to bottom-right)
        for row in range(2):
            for col in range(2):
                if all(self.board[row+i][col+i] == player for i in range(4)):
                    return True

        # 4. Check anti-diagonals (bottom-left to top-right)
        for row in range(3, 5):
            for col in range(2):
                if all(self.board[row-i][col+i] == player for i in range(4)):
                    return True

        return False

    def is_terminal(self):
        """Returns True if the game is over (win or draw)."""
        if self.check_winner('X'):
            return True, 'X'
        if self.check_winner('O'):
            return True, 'O'
        if not self.get_legal_moves():
            return True, 'Draw'
        return False, None


def test_game_logic():
    print("Starting game logic verification...")
    game = TicTacToe5x5()
    legal_moves = game.get_legal_moves()
    assert len(legal_moves) == 25, f"Expected 25 legal moves on start, got {len(legal_moves)}"
    print("✅ All core game logic checks passed successfully!")


# FIXED: Clean block structure alignment at the absolute left margin (0 spaces)
if __name__ == "__main__":
    test_game_logic()